// Generated by CoffeeScript 1.6.3
var arr;

arr = ["./libs/jquery.js", "./libs/sugar.js", "./libs/oj.js", "./libs/easings.js", "./libs/dirty.js", "./libs/cryptojs.min.js"];

head.js.apply(this, arr);

head(function() {
  var change_text, decrypt, encrypt, iv, salt, txt;
  oj.useGlobally();
  iv = "c7cce0d166262006761b014859b6189998e4277a";
  salt = "s club.. there aint no party like an s-club party";
  encrypt = function(plainText) {
    var ciphertext, encrypted, key, password;
    password = $("#password").val();
    key = CryptoJS.PBKDF2(password, CryptoJS.enc.Hex.parse(salt), {
      keySize: this.keySize,
      iterations: this.iterationCount
    });
    encrypted = CryptoJS.AES.encrypt(plainText, key, {
      iv: CryptoJS.enc.Hex.parse(iv)
    });
    ciphertext = encrypted.ciphertext.toString(CryptoJS.enc.Base64);
    return ciphertext;
  };
  decrypt = function(ciphertext) {
    var cipherParams, decrypted, funya, key, password;
    password = $("#password").val();
    key = CryptoJS.PBKDF2(password, CryptoJS.enc.Hex.parse(salt), {
      keySize: this.keySize,
      iterations: this.iterationCount
    });
    cipherParams = CryptoJS.lib.CipherParams.create({
      ciphertext: CryptoJS.enc.Base64.parse(ciphertext)
    });
    decrypted = CryptoJS.AES.decrypt(cipherParams, key, {
      iv: CryptoJS.enc.Hex.parse(iv)
    });
    return funya = decrypted.toString(CryptoJS.enc.Utf8);
  };
  change_text = function() {
    var ciphertext, plainText, real;
    plainText = $("#text").val();
    ciphertext = encrypt(plainText);
    $("#mixed").val(ciphertext);
    real = decrypt(ciphertext);
    return $("#third").val(real);
  };
  txt = "All the speeches and commentaries betray a gigantic abreaction to the event itself and to the fascination that it exerts. Moral condemnation and the sacred union against terrorism are equal to the prodigious jubilation engendered by witnessing this global superpower being destroyed; better, by seeing it more or less self-destroying, even suiciding spectacularly. Though it is (this superpower) that has, through its unbearable power, engendered all that violence brewing around the world, and therefore this terrorist imagination which -- unknowingly -- inhabits us all.";
  return $("#main").oj(div(function() {
    var h;
    h = window.innerHeight - 80;
    h2(function() {
      return "Frowwn";
    });
    input({
      id: "password",
      type: "text",
      value: "password",
      style: "color:grey; font-size:22px; height:30px; border-radius:4px; border:1px solid steelblue;",
      keyup: function() {
        return change_text();
      }
    });
    return table({
      style: "width:100%; height:" + h + "px; "
    }, function() {
      return tr({
        style: "width:100%; height:100%; "
      }, function() {
        td(function() {
          return textarea({
            id: "text",
            style: "width:100%; height:" + h + "px; font-size:22px;",
            keyup: function() {
              return encrypt();
            }
          }, function() {
            return txt;
          });
        });
        td(function() {
          return textarea({
            id: "mixed",
            style: "width:100%; height:" + h + "px; font-size:22px;"
          });
        });
        return td(function() {
          return textarea({
            id: "third",
            style: "width:100%; height:" + h + "px; font-size:22px;"
          });
        });
      });
    });
  }));
});

/*
//@ sourceMappingURL=index.map
*/
